import type { AnimationConfig } from '../../project/model/project';
export interface AnimationControl{key:string;label:string;type:'number'|'color'|'select'|'boolean';min?:number;max?:number;step?:number;options?:Array<{value:string;label:string}>}
export interface AnimationDefinition{type:string;title:string;description:string;defaults:Record<string,number|string|boolean>;controls?:AnimationControl[];exportModule:string}
export const animationDefinitions:AnimationDefinition[]=[
 {type:'blink',title:'Blink',description:'Мягкое мигание',defaults:{duration:1.5,strength:.45},exportModule:'basic-opacity'},
 {type:'pulse',title:'Pulse',description:'Пульсация размера',defaults:{duration:1.8,strength:.12},exportModule:'basic-transform'},
 {type:'float',title:'Float',description:'Плавное парение',defaults:{duration:2.6,strength:18},exportModule:'basic-transform'},
 {type:'shake',title:'Shake',description:'Дрожание по X и Y',defaults:{duration:.55,strength:8},exportModule:'basic-transform'},
 {type:'vibration',title:'Vibration',description:'Частая мелкая вибрация',defaults:{duration:.12,strength:2},exportModule:'basic-transform'},
 {type:'fade',title:'Fade',description:'Появление и исчезновение',defaults:{duration:2.2,strength:.2},exportModule:'basic-opacity'},
 {type:'swing',title:'Swing',description:'Раскачивание',defaults:{duration:2,strength:5},exportModule:'basic-transform'},
 {type:'bounce',title:'Bounce',description:'Подпрыгивание',defaults:{duration:1.5,strength:20},exportModule:'basic-transform'},
 {type:'flicker',title:'Flicker',description:'Неоновое мерцание',defaults:{duration:1.7,strength:.35},exportModule:'basic-filter'},
 {type:'glitch',title:'Glitch',description:'Цифровой сдвиг',defaults:{duration:.9,strength:5},exportModule:'basic-glitch'},
 {type:'light-sweep',title:'Light Sweep',description:'Световой блик проходит по объекту',exportModule:'light-sweep',defaults:{direction:'left-to-right',duration:2.4,sweepWidth:24,color:'#ffffff',opacity:.85,glowIntensity:18,softness:35,angle:18,pingPong:false},controls:[
  {key:'direction',label:'Direction',type:'select',options:[{value:'left-to-right',label:'Left → Right'},{value:'right-to-left',label:'Right → Left'},{value:'top-to-bottom',label:'Top → Bottom'},{value:'bottom-to-top',label:'Bottom → Top'},{value:'diagonal',label:'Diagonal'}]},
  {key:'duration',label:'Speed, сек.',type:'number',min:.2,max:10,step:.1},{key:'sweepWidth',label:'Sweep width, %',type:'number',min:2,max:80,step:1},{key:'color',label:'Color',type:'color'},{key:'opacity',label:'Opacity',type:'number',min:0,max:1,step:.05},{key:'glowIntensity',label:'Glow intensity',type:'number',min:0,max:80,step:1},{key:'softness',label:'Softness, %',type:'number',min:0,max:90,step:1},{key:'angle',label:'Angle',type:'number',min:-90,max:90,step:1},{key:'pingPong',label:'Ping Pong',type:'boolean'}]},
 {type:'scanline-glitch',title:'Scanline Glitch',description:'Цифровые полосы и RGB-помехи',exportModule:'scanline-glitch',defaults:{intensity:.7,frequency:8,scanlineHeight:5,scanlineSpeed:1.3,rgbSplit:5,horizontalDisplacement:8,verticalDisplacement:3,randomDistortion:.55,glitchDuration:.32},controls:[
  {key:'intensity',label:'Intensity',type:'number',min:0,max:1,step:.05},{key:'frequency',label:'Frequency',type:'number',min:1,max:30,step:1},{key:'scanlineHeight',label:'Scanline height',type:'number',min:1,max:30,step:1},{key:'scanlineSpeed',label:'Scanline speed',type:'number',min:.1,max:10,step:.1},{key:'rgbSplit',label:'RGB split',type:'number',min:0,max:30,step:1},{key:'horizontalDisplacement',label:'Horizontal displacement',type:'number',min:0,max:50,step:1},{key:'verticalDisplacement',label:'Vertical displacement',type:'number',min:0,max:30,step:1},{key:'randomDistortion',label:'Random distortion',type:'number',min:0,max:1,step:.05},{key:'glitchDuration',label:'Glitch duration',type:'number',min:.05,max:3,step:.05}]},
 {type:'neon-pulse',title:'Neon Pulse',description:'Двухцветное пульсирующее свечение',exportModule:'neon-pulse',defaults:{primaryColor:'#ff48dc',secondaryColor:'#54e8ff',glowRadius:22,minGlowIntensity:6,maxGlowIntensity:28,pulseSpeed:2,minBrightness:.8,maxBrightness:1.35,opacity:1,scalePulse:true,scaleAmount:.04},controls:[
  {key:'primaryColor',label:'Primary color',type:'color'},{key:'secondaryColor',label:'Secondary color',type:'color'},{key:'glowRadius',label:'Glow radius',type:'number',min:0,max:100,step:1},{key:'minGlowIntensity',label:'Min glow intensity',type:'number',min:0,max:100,step:1},{key:'maxGlowIntensity',label:'Max glow intensity',type:'number',min:0,max:140,step:1},{key:'pulseSpeed',label:'Pulse speed, сек.',type:'number',min:.1,max:10,step:.1},{key:'minBrightness',label:'Min brightness',type:'number',min:.1,max:3,step:.05},{key:'maxBrightness',label:'Max brightness',type:'number',min:.1,max:4,step:.05},{key:'opacity',label:'Opacity',type:'number',min:0,max:1,step:.05},{key:'scalePulse',label:'Slight scale pulse',type:'boolean'},{key:'scaleAmount',label:'Scale amount',type:'number',min:0,max:.3,step:.01}]},
];
export function createAnimation(type:string):AnimationConfig{const definition=animationDefinitions.find(item=>item.type===type);if(!definition)throw new Error(`Unknown animation: ${type}`);return{id:globalThis.crypto.randomUUID(),type,enabled:true,settings:{...definition.defaults}}}
export const animationName=(type:string)=>`tb-${type}`;
export function usedAnimationModules(animations:AnimationConfig[]){return [...new Set(animations.filter(item=>item.enabled).map(item=>animationDefinitions.find(definition=>definition.type===item.type)?.exportModule).filter(Boolean))] as string[]}
